### PR TITLE
Fix(adjustHue): account for potential negative hue value

### LINKED ISSUE #437: adjustHue bug
I've recently discovered Polished, and just love how elegant it is.
However, I've run into a bug in `adjustHue`, which I reproduced in [this codepen](https://codepen.io/DavidDeprost/pen/BeoMGJ).
I really love how well-organised and accessible the Polished codebase is, so I'll try submit a PR later.

- `polished` version: 3.3.0
- `JSS-in_CSS` library and version: styled-components 4.2.0
- Any relevant JS library and version: React 16.8.6

- Mixin/Helper/Shorthand you were using and how you were using it:

  ```javascript
  adjustHue(-25, 'orange'); // ok
  adjustHue(-25, 'cyan');   // ok
  adjustHue(-25, 'red');    // bug: returns black instead of red hue
  ```

- What you are seeing:

  Due to red having a hue of 0, subtracting anything gives a negative hue value,
  which results in black.

- What you expected to see:

  I expected it to work consistently for all colors, so never returning black instead of the desired hue.
  Hue is a value in [0 to 359], so negative values should cycle through to 359 and remain positive,
  regardless of how much was subtracted.

### PR DESCRIPTION
**Pull request by DavidDeprost**
closes #437

### CODE REVIEW

File: src/internalHelpers/_hslToRgb.js [hunk 1]
```diff
@@ -22,9 +22,9 @@ function hslToRgb(
   }
 
   // formular from https://en.wikipedia.org/wiki/HSL_and_HSV
```
Comment (bhough) [inline src/internalHelpers/_hslToRgb.js]: Typo here we should fix as part of this.

File: src/internalHelpers/_hslToRgb.js [hunk 2]
```diff
@@ -22,9 +22,9 @@ function hslToRgb(
...
-  const huePrime = hue % 360 / 60
+  const huePrime = (((hue % 360) + 360) % 360) / 60 // Corrected for potential negative hue
```
Comment (bhough) [inline src/internalHelpers/_hslToRgb.js]: Instead of an inline comment, might be worth putting a note in the docs on how we handle the potential negative hue.

Comment (DavidDeprost) [reply src/internalHelpers/_hslToRgb.js]: I fixed the typo and removed the comment. I'll try looking into the docs later, when I have a bit more time.

**Comment by DavidDeprost** [comment]
Just added a test to `hslToRgb`. I'm not familiar with jest, so I wasn't entirely sure if `adjustHue` requires tests. I noticed `adjustHue` doesn't have a single "negative" test defined. It should be pretty straightforward to copy the existing tests but with a negative argument.
Let me know if you feel this would be useful.

**Comment by DavidDeprost** [comment]
Just added a test to `hslToRgb`. I'm not familiar with jest, so I wasn't entirely sure if `adjustHue` requires tests. I noticed `adjustHue` doesn't have a single "negative" test defined. It should be pretty straightforward to copy the existing tests but with a negative argument.
Let me know if you feel this would be useful.
